#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"
baseline=scripts/size-baseline.txt
if [[ ! -f "$baseline" || -s "$baseline" ]]; then
  echo 'The empty source size baseline must exist and cannot acquire new allowances.' >&2
  exit 1
fi

# Capture traversal errors before checking; process substitution alone would hide them.
inventory=$(mktemp)
trap 'rm -f "$inventory"' EXIT
find . -type d -name .git -prune -o \( -type f -o -type l \) -print0 > "$inventory"
failed=0
count=0
while IFS= read -r -d '' entry; do
  path=${entry#./}
  # Generated by the documented standalone Tailwind command, not handwritten.
  [[ "$path" == assets/css/site.css ]] && continue
  case "$path" in
    *.html|*.css|*.scss|*.js|*.jsx|*.mjs|*.cjs|*.ts|*.tsx|*.sh|*.py|*.sql) ;;
    *) continue ;;
  esac
  if [[ -L "$path" || ! -f "$path" ]]; then
    printf '%s: source must be a regular file, not a symlink.\n' "$path" >&2
    failed=1
    continue
  fi
  limit=750
  case "$path" in *.test.*|*.spec.*) limit=1000 ;; esac
  lines=$(wc -l < "$path")
  count=$((count + 1))
  if (( lines > limit )); then
    printf '%s: %s lines exceeds %s. Split by responsibility.\n' "$path" "$lines" "$limit" >&2
    failed=1
  fi
done < "$inventory"
if (( failed )); then exit 1; fi
printf 'Size check passed: %s source files; no oversized-file allowances.\n' "$count"
